version: '2'
services:
  itassetui-app:
    image: itassetui
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://itassetui-mysql:3306/itassetui?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://itassetui-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://itassetui-elasticsearch:9200
    ports:
      - 8761:8761
  itassetui-mysql:
    extends:
      file: mysql.yml
      service: itassetui-mysql
  itassetui-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: itassetui-elasticsearch
